### ISSUE TITLE
Releases do not contain required `infrastructure-components.yaml`

### ISSUE THREAD

**Issue by djryanj** [microsoft/cluster-api-provider-azurestackhci#284]
In order for this repo to be usable per the CAPI `InfrastructureProvider` CRD, the release must contain a yaml that defines the components for the infrastructure.

For example, using this:

```yaml
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: azurestackhci
  namespace: caph-system
spec:
    fetchConfig:
      url: https://github.com/microsoft/cluster-api-provider-azurestackhci/releases
    version: v1.1.17
```

Results in the following error:

```
        failed to create repo from provider url for provider "azurestackhci":
        error creating the GitHub repository client: invalid url: a GitHub
        repository url should be in the form
        https://github.com/{owner}/{Repository}/releases/{latest|version-tag}/{componentsClient.yaml}
```

Looking at other providers, this is usually `infrastructure-components.yaml` and even poking through this repo we see that _should_ be generated from a kustomize command as part of the release pipeline, _however_ the release pipeline hasn't been successful in some time.

We can do this manually, but that doesn't seem like a very tenable idea.
